### PR TITLE
register FE

### PR DESCRIPTION
**Pull request by VanThen60hz**
i success for connect APIs for register => check and review my code

### CODE REVIEW

**Review by MrThinkJ — COMMENTED** [review]
Code tay ac the iem, ko xai react di :)))

**Comment by Trainning28** [comment]
Đỉnh đỉnh đỉnh. K hiểu gì nhưng mà thấy đỉnh

**Review by MrThinkJ — COMMENTED** [review]
I think we should use comment by English, understand ?

**Comment by VanThen60hz** [comment]
> I think we should use comment by English, understand ?

my fault, i'm forgot it

**Pull request merged**
